export {
    useLoginUserMutation,
    useRegisterUserMutation,
    api,
    useLogoutMutation,
    useRefreshTokenMutation,
    useUserDetailsQuery,
    useMoviesInfiniteQuery,
    useMovieQuery,
    useLatestMoviesInfiniteQuery,
    useUpcomingMoviesInfiniteQuery,
    useGenresQuery,
    useLanguagesQuery,
    useCinemasQuery,
    useLocationsQuery,
    useCinemaQuery,
    useSlotsByCinemaQuery,
    useSlotsByMovieSlugQuery,
    useSlotDetailsQuery,
    useBookingMutation,
} from './services';

export type {
    LoginRequest,
    LoginResponse,
    SignupRequest,
    SignupResponse,
    Genre,
    Language,
    Movie,
    PaginatedQueryResponse,
} from './services.types';
